# Generated by Django 6.0.3 on 2026-03-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='campanhas/'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='projetos/'),
        ),
    ]
