# Generated by Django 6.0.3 on 2026-05-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0002_alter_campanha_imagem_alter_projeto_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_home', models.CharField(default='Transformando Realidades com Cultura e Ação Social', max_length=200)),
                ('subtitulo_home', models.TextField(default='O Coletivo Favela em Ação atua transformando vidas na comunidade.')),
                ('imagem_home', models.ImageField(blank=True, null=True, upload_to='home/')),
            ],
        ),
    ]
