# Generated by Django 6.0.3 on 2026-05-11 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0003_configuracaosite'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanhaImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='campanhas/galeria/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='ong.campanha')),
            ],
        ),
        migrations.CreateModel(
            name='ProjetoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='projetos/galeria/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='ong.projeto')),
            ],
        ),
    ]
